/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/plant.glb -o src/components/PlantModel.tsx --transform 
Files: public/models/plant.glb [2.22MB] > C:\Users\ivan\UIK\src\components\plant-transformed.glb [323.18KB] (85%)
Author: Gonçalo Miranda (https://sketchfab.com/GoncMira02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/potted-plant-1a68fc8877b847c6834ea29a7e65de7a
Title: Potted Plant
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Potted_Plant_Leaf_0: THREE.Mesh
    Potted_Plant_Dirt_0: THREE.Mesh
    Potted_Plant_Pot_0: THREE.Mesh
    Potted_Plant_Plant_0: THREE.Mesh
  }
  materials: {
    Leaf: THREE.MeshStandardMaterial
    Dirt: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Plant: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/plant-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Potted_Plant_Leaf_0.geometry} material={materials.Leaf} />
      <mesh geometry={nodes.Potted_Plant_Dirt_0.geometry} material={materials.Dirt} />
      <mesh geometry={nodes.Potted_Plant_Pot_0.geometry} material={materials.material} />
      <mesh geometry={nodes.Potted_Plant_Plant_0.geometry} material={materials.Plant} />
    </group>
  )
}

useGLTF.preload('/plant-transformed.glb')
