/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pump.glb -o src/components/PumpModel.tsx --transform 
Files: public/models/pump.glb [6.38MB] > C:\Users\ivan\UIK\src\components\pump-transformed.glb [720.1KB] (89%)
Author: Dasamura (https://sketchfab.com/Dasamura)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-water-pressure-booster-pump-41c1a132baf544fa9ffd668bb056f52e
Title: Old Water Pressure Booster Pump
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Pump_Pump_0: THREE.Mesh
  }
  materials: {
    Pump: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/pump-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pump_Pump_0.geometry} material={materials.Pump} position={[-0.08, 0.497, 0.105]} rotation={[-Math.PI / 2, 0, 0]} scale={1.291} />
    </group>
  )
}

useGLTF.preload('/pump-transformed.glb')
